name: Playwright Execution

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests (Generate JUnit)
        run: npx playwright test

      - name: Debug - List Files
        run: ls -R

      - name: Upload JUnit Artifact
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: test-results/e2e-junit-results.xml

      - name: Send JUnit XML to qTest Plus
        if: always()
        run: |
          XML_CONTENT=$(cat test-results/e2e-junit-results.xml | sed 's/"/\\"/g')
          curl -X POST https://pulse-8.qtestnet.com/webhook/19ffba06-a8ce-4c04-a38c-6841441cb0e6 \
          -H "Authorization: Bearer c51e9132-ea8f-4f5a-890c-a189537945bf" \
          -H "Content-Type: application/json" \
          -d "{\"junit\":\"$XML_CONTENT\"}"